SELECT
    CUS.CODPROD    AS CODPROD,
    CUS.CODEMP     AS CODEMP,
    CUS.CODLOCAL   AS CODLOCAL,
    CUS.CONTROLE   AS CONTROLE,
    CUS.DTATUAL    AS DTATUAL,
    CUS.CUSREP     AS CUSREP,
    CUS.DTATUAL    AS ULTDT
FROM
    TGFCUS CUS
WHERE
    CUS.DTATUAL = (
        SELECT
            MAX(C.DTATUAL)
        FROM
            TGFCUS C
        WHERE
            C.CODPROD = CUS.CODPROD
            AND C.CODEMP = CUS.CODEMP
            AND C.CONTROLE = CUS.CONTROLE
            AND C.DTATUAL >= CUS.DTATUAL
    )
ORDER BY
    CUS.CODEMP,
    CUS.CODPROD,
    CUS.CODLOCAL,
    CUS.CONTROLE