SELECT * FROM (
SELECT
CN.CODPROD, CN.CODEMP AS CODEMP, CN.CODLOCAL AS CODLOCAL, CN.CONTROLE AS CONTROLE
,CN.DTATUAL, CN.CUSREP,
MAX(CN.DTATUAL) OVER (PARTITION BY
CN.CODPROD, CN.CODEMP, CN.CODLOCAL, CN.CONTROLE
ORDER BY
CN.CODPROD, CN.CODEMP, CN.CODLOCAL, CN.CONTROLE
)  ULTDT
FROM TGFCUS CN JOIN TGFPRO PRO ON PRO.CODPROD=CN.CODPROD
                            AND PRO.ativo = 'S'
                            AND PRO.permcompprod = 'S' ) CUS
WHERE CUS.DTATUAL=CUS.ULTDT