SELECT * FROM (
SELECT
CN.CODPROD, CN.CODEMP AS CODEMP, CN.CODLOCAL AS CODLOCAL, CN.CONTROLE AS CONTROLE
,CN.DTATUAL, CN.CUSREP,
MAX(CN.DTATUAL) OVER (PARTITION BY
CN.CODPROD, CN.CODEMP, CN.CODLOCAL, CN.CONTROLE
ORDER BY
CN.CODPROD, CN.CODEMP, CN.CODLOCAL, CN.CONTROLE
)  ULTDT
FROM TGFCUS CN ) CUS
WHERE CUS.DTATUAL=CUS.ULTDT